In [1]:
from setup1 import *
from nxspe import *
from crystal_structure import *
import time

In [6]:
data_path = '/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/autoreduce/'
outdir = '/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/NaBr_yshen/own_code/'

# all
data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118964)]
list_psi = np.hstack((np.arange(11, 112), np.arange(11.5, 111)))

# single
#data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118764)]
#list_psi = [11]

# two
#data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118765)]
#list_psi = [11, 12]

assert len(list_psi) == len(data_files)

c = crystal_structure( 'crystal_structure.info' )
uv_to_rlu = c.get_UB_matrix_inv()
print(uv_to_rlu)

[[ -7.67872277e-33   6.63707561e-01  -6.63707561e-01]
 [  7.67872277e-33   6.63707561e-01   6.63707561e-01]
 [  9.38624235e-01   1.47372683e-16  -6.60919492e-17]]


In [8]:
t1 = time.time()
for file, psi in zip(data_files, list_psi):
    start = time.time()
    n = nxspe(file, override_psi=psi)
    n.write_to_csv_while_converting(uv_to_rlu, outdir=outdir, keep_zeros=True)
    end = time.time()
    print('Processed', file[-25:], 'in', '%.2f'%(end-start), 'seconds.')
t2 = time.time()
print('Total time collasped:', '%.2f'%(t2-t1), 'seconds, for', len(data_files), 'files.')

Processed _118763_autoreduced.nxspe in 21.98 seconds.
Processed _118764_autoreduced.nxspe in 21.14 seconds.
Processed _118765_autoreduced.nxspe in 21.27 seconds.
Processed _118766_autoreduced.nxspe in 21.70 seconds.
Processed _118767_autoreduced.nxspe in 21.24 seconds.
Processed _118768_autoreduced.nxspe in 21.21 seconds.
Processed _118769_autoreduced.nxspe in 21.83 seconds.
Processed _118770_autoreduced.nxspe in 21.88 seconds.
Processed _118771_autoreduced.nxspe in 21.54 seconds.
Processed _118772_autoreduced.nxspe in 21.36 seconds.
Processed _118773_autoreduced.nxspe in 22.43 seconds.
Processed _118774_autoreduced.nxspe in 21.14 seconds.
Processed _118775_autoreduced.nxspe in 21.33 seconds.
Processed _118776_autoreduced.nxspe in 22.69 seconds.
Processed _118777_autoreduced.nxspe in 21.33 seconds.
Processed _118778_autoreduced.nxspe in 21.48 seconds.
Processed _118779_autoreduced.nxspe in 21.43 seconds.
Processed _118780_autoreduced.nxspe in 21.92 seconds.
Processed _118781_autoreduce

Processed _118915_autoreduced.nxspe in 22.35 seconds.
Processed _118916_autoreduced.nxspe in 21.44 seconds.
Processed _118917_autoreduced.nxspe in 22.58 seconds.
Processed _118918_autoreduced.nxspe in 22.44 seconds.
Processed _118919_autoreduced.nxspe in 21.31 seconds.
Processed _118920_autoreduced.nxspe in 22.41 seconds.
Processed _118921_autoreduced.nxspe in 21.15 seconds.
Processed _118922_autoreduced.nxspe in 21.39 seconds.
Processed _118923_autoreduced.nxspe in 21.25 seconds.
Processed _118924_autoreduced.nxspe in 21.34 seconds.
Processed _118925_autoreduced.nxspe in 21.58 seconds.
Processed _118926_autoreduced.nxspe in 21.01 seconds.
Processed _118927_autoreduced.nxspe in 21.22 seconds.
Processed _118928_autoreduced.nxspe in 21.54 seconds.
Processed _118929_autoreduced.nxspe in 21.14 seconds.
Processed _118930_autoreduced.nxspe in 21.49 seconds.
Processed _118931_autoreduced.nxspe in 21.68 seconds.
Processed _118932_autoreduced.nxspe in 20.78 seconds.
Processed _118933_autoreduce

In [5]:
n.intensity

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [6]:
n.fname

'/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/autoreduce/ARCS_118763_autoreduced.nxspe'

In [13]:
f = h5.File('/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/autoreduce/ARCS_118863_autoreduced.nxspe','r')

In [8]:
entry = list(f.keys())[0]

In [18]:
np.sum(1-np.isnan(np.array( f[entry+'/data/data'] )))

7389760

In [4]:
c.u

array([ 0.,  0.,  1.])

In [5]:
c.crystal_info

array([[  5.89755,   5.89755,   5.89755],
       [ 90.     ,  90.     ,  90.     ],
       [  0.     ,   0.     ,   1.     ],
       [  1.     ,   1.     ,   0.     ]])

In [4]:
c.B

array([[  1.06538907e+00,  -1.71327629e-16,  -1.71327629e-16],
       [  0.00000000e+00,   1.06538907e+00,  -6.52362657e-17],
       [  0.00000000e+00,   0.00000000e+00,   1.69561937e-01]])

In [13]:
c.alatt_

array([ 0.16956194,  0.16956194,  0.16956194])

In [14]:
c.ang

array([ 1.57079633,  1.57079633,  1.57079633])