In [38]:
import os
os.chdir('/Users/clairensaunders/Code/INS-code/src')

from all_nxspe_v2 import *
from crystal_structure import *

In [39]:
data_path = '/Users/clairensaunders/Documents/Caltech/Research/Cu2O/cuprite_arcs/10K/'
outdir = '/Users/clairensaunders/Documents/Caltech/Research/Cu2O/cuprite_arcs/10K_test/out/'

import glob
data_files = glob.glob( data_path + '*.nxspe' )
print ('Got', str(len(data_files)), 'files with extension *.nxspe' )      
c = crystal_structure( data_path + 'crystal_structure.info' )
uv_to_rlu = c.get_UB_matrix_inv()
print ( uv_to_rlu )
print ( type(uv_to_rlu) )

Got 154 files with extension *.nxspe
[[ 0.66775678  0.00089826 -0.10366395]
 [ 0.02758364  0.64983218  0.18331234]
 [ 0.0999308  -0.18537385  0.64210319]]
<class 'numpy.ndarray'>


In [40]:
t1 = time.time()

for file in data_files:
    start = time.time()
    n = nxspe(file)
    n.temp_store_data ( uv_to_rlu, outdir=outdir+'nv3/' )
    end = time.time()
    print('Processed', file[-25:], 'in', '%.2f'%(end-start), 'seconds.')
t2 = time.time()
print('Total time collasped:', '%.2f'%(t2-t1), 'seconds, for', len(data_files), 'files.')

Processed /10K/cu20_10K_62p50.nxspe in 2.71 seconds.
Processed /10K/cu20_10K_63p50.nxspe in 2.83 seconds.
Processed /10K/cu20_10K_39p00.nxspe in 2.86 seconds.
Processed /10K/cu20_10K_38p00.nxspe in 2.73 seconds.
Processed s/10K/cu20_10K_8p00.nxspe in 2.77 seconds.
Processed s/10K/cu20_10K_9p00.nxspe in 2.53 seconds.
Processed /10K/cu20_10K_87p50.nxspe in 2.79 seconds.
Processed /10K/cu20_10K_86p50.nxspe in 2.93 seconds.
Processed /10K/cu20_10K_94p00.nxspe in 2.77 seconds.
Processed /10K/cu20_10K_73p51.nxspe in 2.96 seconds.
Processed s/10K/cu20_10K_3p00.nxspe in 2.63 seconds.
Processed /10K/cu20_10K_33p00.nxspe in 2.65 seconds.
Processed s/10K/cu20_10K_4p99.nxspe in 2.45 seconds.
Processed /10K/cu20_10K_32p00.nxspe in 2.74 seconds.
Processed /10K/cu20_10K_68p50.nxspe in 2.60 seconds.
Processed /10K/cu20_10K_69p50.nxspe in 2.59 seconds.
Processed /10K/cu20_10K_-4p01.nxspe in 2.56 seconds.
Processed /10K/cu20_10K_56p50.nxspe in 2.63 seconds.
Processed /10K/cu20_10K_57p50.nxspe in 2.73 se

KeyboardInterrupt: 