In [1]:
from all_nxspe import *
from crystal_structure import *

In [2]:
data_path = '/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/autoreduce/'
outdir = #YOUR PATH#'/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/NaBr_yshen/own_code/'

# all
sc_data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118964)]
bg_data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(119065,119076)]
list_psi = np.hstack((np.arange(11, 112), np.arange(11.5, 111)))
assert len(list_psi) == len(sc_data_files)

c = crystal_structure( 'crystal_structure.info' )
uv_to_rlu = c.get_UB_matrix_inv()
print(uv_to_rlu)

[[ -7.67872277e-33   6.63707561e-01  -6.63707561e-01]
 [  7.67872277e-33   6.63707561e-01   6.63707561e-01]
 [  9.38624235e-01   1.47372683e-16  -6.60919492e-17]]


In [3]:
bg_n = get_bg_nxspe(bg_data_files, ein=30.0)
W = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])
t1 = time.time()
for file, psi in zip(sc_data_files, list_psi):
    start = time.time()
    n = nxspe_with_bg(file, bg_n, override_psi=psi, ein=30.0)
    n.write_to_csv_while_converting(uv_to_rlu, outdir=outdir+'withbg/', keep_zeros=True, W=W)
    end = time.time()
    print('Processed', file[-25:], 'in', '%.2f'%(end-start), 'seconds.')
t2 = time.time()
print('Total time collasped:', '%.2f'%(t2-t1), 'seconds, for', len(sc_data_files), 'files.')

Processed _118763_autoreduced.nxspe in 25.19 seconds.
Processed _118764_autoreduced.nxspe in 24.66 seconds.
Processed _118765_autoreduced.nxspe in 24.17 seconds.
Processed _118766_autoreduced.nxspe in 24.81 seconds.
Processed _118767_autoreduced.nxspe in 25.07 seconds.
Processed _118768_autoreduced.nxspe in 24.79 seconds.
Processed _118769_autoreduced.nxspe in 25.77 seconds.
Processed _118770_autoreduced.nxspe in 24.84 seconds.
Processed _118771_autoreduced.nxspe in 25.67 seconds.
Processed _118772_autoreduced.nxspe in 24.75 seconds.
Processed _118773_autoreduced.nxspe in 25.18 seconds.
Processed _118774_autoreduced.nxspe in 24.70 seconds.
Processed _118775_autoreduced.nxspe in 24.45 seconds.
Processed _118776_autoreduced.nxspe in 24.84 seconds.
Processed _118777_autoreduced.nxspe in 25.26 seconds.
Processed _118778_autoreduced.nxspe in 25.73 seconds.
Processed _118779_autoreduced.nxspe in 25.11 seconds.
Processed _118780_autoreduced.nxspe in 25.11 seconds.
Processed _118781_autoreduce

Processed _118915_autoreduced.nxspe in 24.57 seconds.
Processed _118916_autoreduced.nxspe in 25.10 seconds.
Processed _118917_autoreduced.nxspe in 25.64 seconds.
Processed _118918_autoreduced.nxspe in 25.66 seconds.
Processed _118919_autoreduced.nxspe in 24.29 seconds.
Processed _118920_autoreduced.nxspe in 24.33 seconds.
Processed _118921_autoreduced.nxspe in 24.25 seconds.
Processed _118922_autoreduced.nxspe in 24.58 seconds.
Processed _118923_autoreduced.nxspe in 24.27 seconds.
Processed _118924_autoreduced.nxspe in 24.11 seconds.
Processed _118925_autoreduced.nxspe in 24.56 seconds.
Processed _118926_autoreduced.nxspe in 24.90 seconds.
Processed _118927_autoreduced.nxspe in 25.39 seconds.
Processed _118928_autoreduced.nxspe in 24.05 seconds.
Processed _118929_autoreduced.nxspe in 24.95 seconds.
Processed _118930_autoreduced.nxspe in 25.24 seconds.
Processed _118931_autoreduced.nxspe in 25.08 seconds.
Processed _118932_autoreduced.nxspe in 24.10 seconds.
Processed _118933_autoreduce

NameError: name 'data_files' is not defined