In [1]:
from setup1 import *
from all_nxspe import *
from crystal_structure import *
import time

In [2]:
data_path = '/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/autoreduce/'
outdir = #YOUR PATH# '/SNS/users/yshen/data/SNS/ARCS/IPTS-20963/shared/NaBr_yshen/own_code/'

# all
data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118964)]
list_psi = np.hstack((np.arange(11, 112), np.arange(11.5, 111)))

# single
#data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118764)]
#list_psi = [11]

# two
#data_files = [data_path+'ARCS_'+str(i)+'_autoreduced.nxspe' for i in range(118763,118765)]
#list_psi = [11, 12]

assert len(list_psi) == len(data_files)

c = crystal_structure( 'crystal_structure.info' )
uv_to_rlu = c.get_UB_matrix_inv()
print(uv_to_rlu)

[[ -7.67872277e-33   6.63707561e-01  -6.63707561e-01]
 [  7.67872277e-33   6.63707561e-01   6.63707561e-01]
 [  9.38624235e-01   1.47372683e-16  -6.60919492e-17]]


In [3]:
W = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])
t1 = time.time()
for file, psi in zip(data_files, list_psi):
    start = time.time()
    n = nxspe(file, override_psi=psi, ein=30.0)
    n.write_to_csv_while_converting(uv_to_rlu, outdir=outdir+'nv3/', keep_zeros=True, W=W)
    end = time.time()
    print('Processed', file[-25:], 'in', '%.2f'%(end-start), 'seconds.')
t2 = time.time()
print('Total time collasped:', '%.2f'%(t2-t1), 'seconds, for', len(data_files), 'files.')

t1 = time.time()
for file, psi in zip(data_files, list_psi):
    start = time.time()
    n = nxspe(file, override_psi=psi, ein=30.0)
    n.write_to_csv_while_converting(uv_to_rlu, outdir=outdir+'nv3/', keep_zeros=False, W=W)
    end = time.time()
    print('Processed', file[-25:], 'in', '%.2f'%(end-start), 'seconds.')
t2 = time.time()
print('Total time collasped:', '%.2f'%(t2-t1), 'seconds, for', len(data_files), 'files.')

Processed _118763_autoreduced.nxspe in 22.10 seconds.
Processed _118764_autoreduced.nxspe in 21.93 seconds.
Processed _118765_autoreduced.nxspe in 22.21 seconds.
Processed _118766_autoreduced.nxspe in 21.79 seconds.
Processed _118767_autoreduced.nxspe in 22.21 seconds.
Processed _118768_autoreduced.nxspe in 21.89 seconds.
Processed _118769_autoreduced.nxspe in 22.87 seconds.
Processed _118770_autoreduced.nxspe in 22.22 seconds.
Processed _118771_autoreduced.nxspe in 22.42 seconds.
Processed _118772_autoreduced.nxspe in 22.20 seconds.
Processed _118773_autoreduced.nxspe in 22.32 seconds.
Processed _118774_autoreduced.nxspe in 21.96 seconds.
Processed _118775_autoreduced.nxspe in 21.95 seconds.
Processed _118776_autoreduced.nxspe in 21.96 seconds.
Processed _118777_autoreduced.nxspe in 22.03 seconds.
Processed _118778_autoreduced.nxspe in 22.01 seconds.
Processed _118779_autoreduced.nxspe in 21.99 seconds.
Processed _118780_autoreduced.nxspe in 21.96 seconds.
Processed _118781_autoreduce

Processed _118915_autoreduced.nxspe in 23.42 seconds.
Processed _118916_autoreduced.nxspe in 23.33 seconds.
Processed _118917_autoreduced.nxspe in 22.88 seconds.
Processed _118918_autoreduced.nxspe in 22.30 seconds.
Processed _118919_autoreduced.nxspe in 22.60 seconds.
Processed _118920_autoreduced.nxspe in 24.64 seconds.
Processed _118921_autoreduced.nxspe in 22.15 seconds.
Processed _118922_autoreduced.nxspe in 22.70 seconds.
Processed _118923_autoreduced.nxspe in 21.98 seconds.
Processed _118924_autoreduced.nxspe in 22.09 seconds.
Processed _118925_autoreduced.nxspe in 22.46 seconds.
Processed _118926_autoreduced.nxspe in 22.54 seconds.
Processed _118927_autoreduced.nxspe in 22.38 seconds.
Processed _118928_autoreduced.nxspe in 22.60 seconds.
Processed _118929_autoreduced.nxspe in 22.44 seconds.
Processed _118930_autoreduced.nxspe in 22.35 seconds.
Processed _118931_autoreduced.nxspe in 23.36 seconds.
Processed _118932_autoreduced.nxspe in 22.65 seconds.
Processed _118933_autoreduce

Processed _118867_autoreduced.nxspe in 4.02 seconds.
Processed _118868_autoreduced.nxspe in 3.94 seconds.
Processed _118869_autoreduced.nxspe in 4.86 seconds.
Processed _118870_autoreduced.nxspe in 4.58 seconds.
Processed _118871_autoreduced.nxspe in 6.94 seconds.
Processed _118872_autoreduced.nxspe in 6.28 seconds.
Processed _118873_autoreduced.nxspe in 4.70 seconds.
Processed _118874_autoreduced.nxspe in 4.69 seconds.
Processed _118875_autoreduced.nxspe in 4.00 seconds.
Processed _118876_autoreduced.nxspe in 5.46 seconds.
Processed _118877_autoreduced.nxspe in 4.25 seconds.
Processed _118878_autoreduced.nxspe in 5.08 seconds.
Processed _118879_autoreduced.nxspe in 3.57 seconds.
Processed _118880_autoreduced.nxspe in 3.92 seconds.
Processed _118881_autoreduced.nxspe in 4.32 seconds.
Processed _118882_autoreduced.nxspe in 4.82 seconds.
Processed _118883_autoreduced.nxspe in 3.96 seconds.
Processed _118884_autoreduced.nxspe in 3.37 seconds.
Processed _118885_autoreduced.nxspe in 5.79 se